spring:
  application:
    name: turbine

server:
  port: 8989

management:
  port: 8990

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring:1300/eureka/, http://summer:1301/eureka/

turbine:
  app-config: WEB, USER-SERVICE, BOOK-SERVICE
  cluster-name-expression: default
  combine-host-port: true

logging:
  file: ${spring.application.name}.log
