spring:
  application:
    name: web

logging:
  file: ${spring.application.name}.log

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring:1300/eureka/, http://summer:1301/eureka/

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 500
  ReadTimeout: 7000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000

# 全局关闭hystrix支持
#feign.hystrix.enabled=false

# hystrix的默认配置
#hystrix.command.default.execution.timeout.enabled=true
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=1000

# hystrix指定Commandkey的配置
#hystrix.command.hello.execution.isolation.thread.timeoutInMilliseconds=5000

# ribbon指定服务的配置
#HELLO-SERVICE.ribbon.ReadTimeout=2000

# ribbon默认配置
#ribbon.ConnectTimeout=250
#ribbon.ReadTimeout=1000
#ribbon.OkToRetryOnAllOperations=true
#ribbon.MaxAutoRetriesNextServer=2
#ribbon.MaxAutoRetries=0

# feign日志配置
#logging.level.com.didispace.web.HelloService=DEBUG


