spring:
  application:
    name: user-service

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring:1300/eureka/,http://summer:1301/eureka/

hikari:
  user:
    jdbcUrl: jdbc:mysql://spring:3306/user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver


