spring:
  application:
    name: user-service

server:
  port: 8081

logging:
  file: ${spring.application.name}.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring:1300/eureka/

hikari:
  user:
    jdbcUrl: jdbc:mysql://spring:3306/user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver




