spring:
  application:
    name: user-service

  redis:
    # database: 5
    host: spring
    password: 123456
    port: 6379
    timeout: 3000
    pool:
      max-idle: 500
      min-idle: 50
      max-active: 2000
      max-wait: 1000

server:
  port: 8081

logging:
  file: ${spring.application.name}.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring:1300/eureka/

hikari:
  user:
    jdbcUrl: jdbc:mysql://spring:3306/user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver


